# MOSTLY AI

## Installation

Use `pip` (or preferably `uv pip`) to install the official `MostlyAI` package via PyPI. Python 3.10 or higher is required.  

We use `mostlyai[local]` to install the LOCAL mode, which trains and generates synthetic data locally on our own compute resources.  

After installing, you might need to restart your kernel

In [1]:
# %pip install 'mostlyai[local]'

## Load Original Data

Fetch some original data that will be used for training the generator.

In [2]:
import pandas as pd

In [3]:
positions_df = pd.read_csv("../input_data/denmark_positions_downsampled.csv")
trips_df = pd.read_csv("../input_data/denmark_trips_downsampled.csv")

In [4]:
trips_df = trips_df[['TRIP_ID']]
trips_df

      TRIP_ID
0           8
1           9
2          10
3          11
4          24
...       ...
4399     4996
4400     4997
4401     4998
4402     4999
4403     5000

[4404 rows x 1 columns]

In [5]:
positions_df = positions_df[['POSITION_ID', 'POSITION_TRIP_ID', 'LAT_LONG']]
positions_df

        POSITION_ID  POSITION_TRIP_ID              LAT_LONG
0                 0                 8  55.508922, 15.458938
1                 3                 8  55.500105, 15.452538
2                 9                 8  55.492128, 15.444578
3                14                 8   55.482085, 15.43882
4                23                 8  55.471972, 15.432787
...             ...               ...                   ...
464300      8533070              5000  54.534398, 13.936615
464301      8533086              5000    54.542833, 13.9285
464302      8533096              5000   54.550905, 13.92056
464303      8533103              5000  54.564587, 13.906743
464304      8533104              5000      54.5835, 13.8875

[464305 rows x 3 columns]

## Initialize the SDK

In [6]:
from mostlyai.sdk import MostlyAI

# initialize SDK
mostly = MostlyAI(local=True)

Initializing Synthetic Data SDK 4.5.2 in LOCAL mode 🏠

Connected to ]8;id=33096;file:///home/ninacv/mostlyai\/home/ninacv/]8;;\]8;id=342301;file:///home/ninacv/mostlyai\mostlyai]8;;\ with 15 GB RAM, 20 CPUs, 1x NVIDIA RTX A1000 6GB Laptop GPU available

## Train a Generator

Train a synthetic data generator.

In [7]:
g = mostly.train(
    config={
        "name": "Vessel Trip Generator",
        "tables": [
            {
                "name": "trips",
                "data": trips_df,
                "tabular_model_configuration": {
                    # "max_training_time": 1,  # - limit training time (in minutes)
                    "model": "MOSTLY_AI/Large",
                },
                "primary_key": "TRIP_ID",
                "columns": [{"name": "TRIP_ID"}],
            },
            {
                "name": "positions",
                "data": positions_df,
                "tabular_model_configuration": {
                    # "max_training_time": 1,  # - limit training time (in minutes)
                    "model": "MOSTLY_AI/Large"
                },
                "columns": [
                    {"name": "POSITION_ID"},
                    {"name": "POSITION_TRIP_ID"},
                    {
                        "name": "LAT_LONG",
                        "model_encoding_type": "TABULAR_LAT_LONG",
                    },
                ],
                "primary_key": "POSITION_ID",
                "foreign_keys": [
                    {
                        "column": "POSITION_TRIP_ID",
                        "referenced_table": "trips",
                        "is_context": True,
                    }
                ],
            },
        ],
    },
    start=True,
    wait=True
)

Created generator cea5e846-fff6-4b03-b5ea-513a766218da

Started generator training

Output()

/home/ninacv/Code/mostlyai-synthetic-vessel-trajectories/.venv/lib/python3.12/site-packages/mostlyai/qa/_coherence.py:95: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

/home/ninacv/Code/mostlyai-synthetic-vessel-trajectories/.venv/lib/python3.12/site-packages/mostlyai/qa/_coherence.py:117: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

/home/ninacv/Code/mostlyai-synthetic-vessel-trajectories/.venv/lib/python3.12/site-packages/mostlyai/qa/_coherence.py:95: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

/home/ninacv/Code/mostlyai-synthetic-vessel-trajectories/.venv/lib/python3.12/site-packages/mostlyai/qa/_coherence.py:117: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

🎉 Your generator is ready! Use it to create synthetic data. Publish it so others can do the same.

### Export generator to file

You can export a generator to a ZIP archive with the `export_to_file()` method. The generator is exported as a ZIP archive.

In [ ]:
# g.export_to_file('generator/1903-denmark-generator.zip')

## Generate Synthetic Data

Probe the trained generator for 100 representative synthetic samples.

In [8]:
df_samples = mostly.probe(g, size=1000)
df_samples

{'trips':                                   TRIP_ID
 0    mostly16-a7b2-4a3d-b510-d548b554c6f6
 1    mostly58-3cee-4995-8c14-1a1715bb1342
 2    mostlyee-88d5-4118-8360-7dc299c88d16
 3    mostlyfe-7bab-4161-a5a8-c087fb481c4c
 4    mostlyc2-79e5-41f8-8fb6-46cd2b999ced
 ..                                    ...
 995  mostly42-9ca0-4688-bf05-b5581e502ef0
 996  mostlyb5-f05c-40e3-8a22-b5d22a173939
 997  mostlycc-7b85-41f3-8496-e5fd0f0794ab
 998  mostly71-e0d5-44b7-8e55-b6e0f3070845
 999  mostly8a-202d-4070-b79e-f8c42a432ab5

 [1000 rows x 1 columns],
 'positions':                                  POSITION_ID  \
 0       mostly65-ddd4-44e6-bb68-99a42fb91d56
 1       mostlybc-b496-4020-86cd-7e694cf1b7af
 2       mostly54-09e9-4d73-8b3f-355cfb40a066
 3       mostly69-7fc3-4205-8818-d02fbf58be11
 4       mostly12-85ab-41d1-b36a-684745226811
 ...                                      ...
 102638  mostlya4-782f-4073-bd4c-ab1fbf5d10a7
 102639  mostly1f-a1bb-481a-a7af-733a1fffa85a
 102640  mostly97-69c1-4c94-b7bd-3769d5aeeebd
 102641  mostly9e-38a7-4fd0-86f2-e1f6696982cb
 102642  mostlyb6-002b-446b-8814-f11309f20c4d

                             POSITION_TRIP_ID            LAT_LONG
 0       mostlye8-6e9d-4e46-84ed-a8b4a0c49fc6  55.80613, 15.99169
 1       mostly03-da1b-4fc6-a858-a73caec393d9  54.60081, 13.76175
 2       mostly71-1820-4dbd-810d-f7d85bf330aa  55.24976, 13.34635
 3       mostlyfd-9447-4bb8-ac80-75701996d7e6  54.78684, 13.58962
 4       mostlyf3-1b01-44f0-b457-25b1a7722d8f  55.89930, 15.99703
 ...                                      ...                 ...
 102638  mostly90-fb35-40c9-971c-aa153eed0df2  54.51118, 13.77501
 102639  mostlyf2-2cc9-4449-838d-62eddb2e12fd  54.82065, 15.97347
 102640  mostly68-d385-41bc-b1e6-06abf3531736  55.42377, 14.72933
 102641  mostly3f-86b6-452c-9b16-fc47e0e2d302  54.85172, 13.06451
 102642  mostlye8-e93b-4038-9aba-f6c215bcc124  54.92323, 13.64378

 [102643 rows x 3 columns]}

In [9]:
syn_positions = df_samples["positions"]
syn_positions

,POSITION_ID,POSITION_TRIP_ID,LAT_LONG
0,mostly65-ddd4-44e6-bb68-99a42fb91d56,mostlye8-6e9d-4e46-84ed-a8b4a0c49fc6,"55.80613, 15.99169"
1,mostlybc-b496-4020-86cd-7e694cf1b7af,mostly03-da1b-4fc6-a858-a73caec393d9,"54.60081, 13.76175"
2,mostly54-09e9-4d73-8b3f-355cfb40a066,mostly71-1820-4dbd-810d-f7d85bf330aa,"55.24976, 13.34635"
3,mostly69-7fc3-4205-8818-d02fbf58be11,mostlyfd-9447-4bb8-ac80-75701996d7e6,"54.78684, 13.58962"
4,mostly12-85ab-41d1-b36a-684745226811,mostlyf3-1b01-44f0-b457-25b1a7722d8f,"55.89930, 15.99703"
...,...,...,...
102638,mostlya4-782f-4073-bd4c-ab1fbf5d10a7,mostly90-fb35-40c9-971c-aa153eed0df2,"54.51118, 13.77501"
102639,mostly1f-a1bb-481a-a7af-733a1fffa85a,mostlyf2-2cc9-4449-838d-62eddb2e12fd,"54.82065, 15.97347"
102640,mostly97-69c1-4c94-b7bd-3769d5aeeebd,mostly68-d385-41bc-b1e6-06abf3531736,"55.42377, 14.72933"
102641,mostly9e-38a7-4fd0-86f2-e1f6696982cb,mostly3f-86b6-452c-9b16-fc47e0e2d302,"54.85172, 13.06451"
102642,mostlyb6-002b-446b-8814-f11309f20c4d,mostlye8-e93b-4038-9aba-f6c215bcc124,"54.92323, 13.64378"

In [10]:
ps = pd.DataFrame(syn_positions)
ps.to_csv("../synthetic_data/denmark_syn_positions.csv")

In [11]:
# Splitting into latitude and longitude
ps[['LATITUDE', 'LONGITUDE']] = ps['LAT_LONG'].str.split(', ', expand=True)

# Convert to float
ps['LATITUDE'] = ps['LATITUDE'].astype(float)
ps['LONGITUDE'] = ps['LONGITUDE'].astype(float)

ps.to_csv("../synthetic_data/denmark_syn_positions.csv")
ps

,POSITION_ID,POSITION_TRIP_ID,LAT_LONG,LATITUDE,LONGITUDE
0,mostly65-ddd4-44e6-bb68-99a42fb91d56,mostlye8-6e9d-4e46-84ed-a8b4a0c49fc6,"55.80613, 15.99169",55.80613,15.99169
1,mostlybc-b496-4020-86cd-7e694cf1b7af,mostly03-da1b-4fc6-a858-a73caec393d9,"54.60081, 13.76175",54.60081,13.76175
2,mostly54-09e9-4d73-8b3f-355cfb40a066,mostly71-1820-4dbd-810d-f7d85bf330aa,"55.24976, 13.34635",55.24976,13.34635
3,mostly69-7fc3-4205-8818-d02fbf58be11,mostlyfd-9447-4bb8-ac80-75701996d7e6,"54.78684, 13.58962",54.78684,13.58962
4,mostly12-85ab-41d1-b36a-684745226811,mostlyf3-1b01-44f0-b457-25b1a7722d8f,"55.89930, 15.99703",55.89930,15.99703
...,...,...,...,...,...
102638,mostlya4-782f-4073-bd4c-ab1fbf5d10a7,mostly90-fb35-40c9-971c-aa153eed0df2,"54.51118, 13.77501",54.51118,13.77501
102639,mostly1f-a1bb-481a-a7af-733a1fffa85a,mostlyf2-2cc9-4449-838d-62eddb2e12fd,"54.82065, 15.97347",54.82065,15.97347
102640,mostly97-69c1-4c94-b7bd-3769d5aeeebd,mostly68-d385-41bc-b1e6-06abf3531736,"55.42377, 14.72933",55.42377,14.72933
102641,mostly9e-38a7-4fd0-86f2-e1f6696982cb,mostly3f-86b6-452c-9b16-fc47e0e2d302,"54.85172, 13.06451",54.85172,13.06451
102642,mostlyb6-002b-446b-8814-f11309f20c4d,mostlye8-e93b-4038-9aba-f6c215bcc124,"54.92323, 13.64378",54.92323,13.64378

# Save and Load existing generator

In [1]:
from mostlyai.sdk import MostlyAI

# initialize SDK
mostly = MostlyAI(local=True)

Initializing Synthetic Data SDK 4.3.3 in LOCAL mode 🏠

Connected to ]8;id=141631;file:///home/ninacv/mostlyai\/home/ninacv/]8;;\]8;id=295887;file:///home/ninacv/mostlyai\mostlyai]8;;\ with 15 GB RAM, 20 CPUs, 1x NVIDIA RTX A1000 6GB Laptop GPU available

# Save and Load generators

You can import a generator with the `import_from_file()` method.

In [ ]:
# g = mostly.generators.import_from_file('generator/1903-denmark-generator.zip')